### GET All CATS
GET http://localhost:8080/api/v1/cats
Authorization: Basic user user
Accept: application/json

### GET ONE CAT
GET http://localhost:8080/api/v1/cats/user
Authorization: Basic user user
Accept: application/json
Accept: text/plain

### DEL 1 ITEM
DELETE http://localhost:8080/api/v1/cats/2
Authorization: Basic admin admin
Accept: application/json
###